services:
    node-site:
        build: .
        environment:
            - VIRTUAL_HOST=node.pajordan.com
            - LETSENCRYPT_HOST=node.pajordan.com
        networks:
            - net
        container_name: node-site
networks:
    net:
        external: true
        name: net
